# Generated by Django 5.0.6 on 2024-07-24 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_profile_address_alter_profile_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
