# Generated by Django 5.0.6 on 2024-09-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_profile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurnPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=100, unique=True)),
                ('churn_rate', models.FloatField()),
                ('recommended_products', models.TextField()),
                ('contract', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('tenure', models.IntegerField()),
                ('payment_method', models.CharField(max_length=50)),
                ('date_predicted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
