# Generated by Django 5.0.6 on 2024-11-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_churnprediction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='churnprediction',
            old_name='date_predicted',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='churnprediction',
            name='churn_rate',
        ),
        migrations.RemoveField(
            model_name='churnprediction',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='churnprediction',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='churnprediction',
            name='recommended_products',
        ),
        migrations.AddField(
            model_name='churnprediction',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='churnprediction',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='churnprediction',
            name='prediction_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churnprediction',
            name='prediction_output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churnprediction',
            name='recommendations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='churnprediction',
            name='senior_citizen',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='churnprediction',
            name='total_day_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='churnprediction',
            name='total_eve_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='churnprediction',
            name='total_intl_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='churnprediction',
            name='total_night_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='churnprediction',
            name='customer_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='churnprediction',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='churnprediction',
            name='tenure',
            field=models.IntegerField(default=0),
        ),
    ]
